name: 'google-chat-github-notification'
description: 'Google Chat Notification for GitHub Actions'
author: 'CommonMarvel'
branding:
  icon: 'at-sign'
  color: 'yellow'
inputs:
  url:
    description: 'google chat webhook url.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
